### ISSUE TITLE
KDL 1.0 Compliance

### ISSUE THREAD

**Issue by zkat** [kdl-org/kdl4j#3]
Hi! Since this was originally written, KDL has stabilized to 1.0.0. No further changes should be made to spec so it should be safe to update + finalize kdl4j to the 1.0 spec!

Please let me know if you have any questions or if there's anything I can do to help!

**Comment by hkolbeck** [comment]
Thanks @zkat! I'll be continuing to try to recruit help, and any assistance with that is much appreciated.

If you're reading this and interested in helping, DM @hbeckpdx on Twitter and let's talk about it.

**Comment by hkolbeck** [comment]
I believe the changes in https://github.com/hkolbeck/kdl4j/pull/4 bring kdl4j into alignment with the 1.0.0 spec. Closing this for now.

**Comment by zkat** [comment]
So cool!! Congratulations!!
